---
title: "bootstrap"
author: "Zilin Huang"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(modelr)

set.seed(1)
```

## Generate a relevant example

```{r}
n_samp = 50

sim_df_const =
  tibble(
    x = rnorm(n_samp, 1, 1),
    error = rnorm(n_samp, 0, 1),
    y = 2 + 3*x + error
  )

sim_df_nonconst =
  sim_df_const |>
  mutate(
    error = error * .75*x,
    y = 2 + 3*x + error
  )

sim_df_nonconst |>
  ggplot(aes(x=x, y=y)) + geom_point()
```

fit linear models

```{r}
sim_df_const |>
  lm(y ~ x, data = _) |>
  broom::tidy()

sim_df_nonconst |>
  lm(y ~ x, data = _) |>
  broom::tidy()
```

## Draw and analyze a bootstrap sample

```{r}
boot_sample = function(df) {
  
  sample_frac(df, replace=TRUE)
  
}
```

```{r}
sim_df_nonconst |>
  boot_sample() |>
  ggplot(aes(x=x, y=y)) +
  geom_point(alpha=.5) +
  stat_smooth(method = "lm")
```

## Draw samples

```{r}
boot_straps = 
  tibble(strap_number = 1:1000) |>
  mutate(
    strap_sample = map(strap_number, \(i) boot_sample(sim_df_nonconst))
  )

boot_straps |>
  pull(strap_sample) |>
  nth(1) |>
  unnest()
```

Now do the `lm` fit

```{r}
boot_results = 
  boot_straps |>
  mutate(
    models = map(strap_sample, \(df) lm(y~x, data=df)),
    results = map(models, broom::tidy)
  ) |>
  select(strap_number, results) |>
  unnest(results)
```

Summarize the results and get a bootstrap Standard Error

```{r}
boot_results |>
  group_by(term) |>
  summarise(
    se = sd(estimate)
  )
```

```{r}
boot_results |>
  filter(term == "x") |>
  ggplot(aes(x = estimate)) +
  geom_density()
```

Construct a CI

```{r}
boot_results |>
  group_by(term) |>
  summarise(
    ci_lower = quantile(estimate, 0.025),
    ci_higher = quantile(estimate, 0.975)
  )
```

## Airbnb

```{r}
data("nyc_airbnb")

nyc_airbnb = 
nyc_airbnb |>
  mutate(
    stars = review_scores_location / 2
  ) |>
  rename(
    borough = neighbourhood_group
  ) |>
  filter(borough != "Staten Island") |>
  drop_na(price, stars) |>
  select(price, stars, room_type, borough)
```

Fit a regression of `price`

```{r}
airbnb_fit = 
nyc_airbnb |>
  lm(price ~ stars + room_type + borough, data = _)

nyc_airbnb |>
  modelr::add_residuals((airbnb_fit)) |>
  ggplot(aes(x=stars, y=resid)) +
  geom_point()
```

```{r}
manhattan_df = 
  nyc_airbnb |>
  filter(borough == "Manhattan")

boot_results =
  tibble(strap_number = 1:1000) |>
  mutate(
    strap_sample = map(strap_number, \(i)boot_sample(manhattan_df)),
    models = map(strap_sample, \(df) lm(price~stars+room_type, data=df)),
    results = map(models, broom::tidy)
  ) |>
    select(strap_number, results) |>
    unnest(results)

boot_results |>
  filter(term == "stars") |>
  ggplot(aes(x=estimate)) +
  geom_density()
```

