---
title: "Untitled"
author: "Zilin Huang"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(modelr)
library(mgcv)

set.seed(1)
```

## Nonlinear data and CV

```{r}
nonlin_df = 
  tibble(
    id = 1:100,
    x = runif(100, 0, 1),
    y = 1 - 10 * (x - .3) ^ 2 + rnorm(100, 0, .3)
  )

nonlin_df |> 
  ggplot(aes(x = x, y = y)) + 
  geom_point()
```

Do the train/test split.

```{r}
train_df = sample_n(nonlin_df, 80)
test_df = anti_join(nonlin_df, train_df, by = "id")
```

```{r}
train_df |>
  ggplot(aes(x=x, y=y)) +
  geom_point() +
  geom_point(data=test_df, color="red")
```

```{r}
linear_mod = lm(y~x, data=train_df)
smooth_mod = mgcv::gam(y~s(x),data=train_df)
wiggly_mod = mgcv::gam(y~s(x, k=30), sp=10e-6, data=train_df)

rmse(linear_mod, train_df)
rmse(smooth_mod, train_df)
rmse(wiggly_mod, train_df)

rmse(linear_mod, test_df)
rmse(smooth_mod, test_df)
rmse(wiggly_mod, test_df)
```

Visualization of the linear model

```{r}
train_df |>
  modelr::add_predictions(wiggly_mod) |>
  ggplot(aes(x=x, y=y)) +
  geom_point() +
  geom_line(aes(y=pred))
```

## Use modelr for CV

```{r}
cv_df = 
  nonlin_df |>
  crossv_mc(n = 100) |>
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble)
  )
```

```{r}
cv_df |>
  pull(train) |>
  nth(1) |>
  as_tibble()
```

Apply each model to all training datasets, and evaluate them.

```{r}
lin_mod_funct = function(df){
  lm(y~x, data=df)
}

cv_results = 
  cv_df |>
  mutate(
    linear_fit = map(train, \(df) lm(y~x, data=df)),
    smooth_fit = map(train, \(df) mgcv::gam(y~s(x), data=df)),
    wiggly_fit = map(train, \(df) mgcv::gam(y~s(x, k=30), sp=10e-6, data=df))
    #linear_fit = map(train, lin_mod_funct)
  ) |>
  mutate(
    rmse_linear = map2_dbl(linear_fit, test, \(mod, df) rmse(mod, df)),
    rmse_smooth = map2_dbl(smooth_fit, test, \(mod, df) rmse(mod, df)),
    rmse_wiggly = map2_dbl(wiggly_fit, test, \(mod, df) rmse(mod, df))
  )
```

```{r}
cv_results |>
  select(starts_with("rmse")) |>
  pivot_longer(
    everything(),
    names_to = "model_type",
    values_to = "rmse",
    names_prefix = "rmse_"
  ) |>
  ggplot(aes(x = model_type, y = rmse)) +
  geom_violin()
```